services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/keisei/data
        target: /var/lib/nginx
  php-fpm:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
