services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    pull_policy: build
    ports:
      - "443:443"
    networks:
      - docker-network
    volumes:
      - wp_data:/var/lib/nginx/html
    secrets:
      - server-certificate
      - server-certificate-key
    restart: always
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    pull_policy: build
    networks:
      - docker-network
    volumes:
      - wp_data:/var/www/html
    env_file: "./requirements/wordpress/.env"
    secrets:
      - db-password
    restart: always
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    pull_policy: build
    networks:
      - docker-network
    volumes:
      - db_data:/var/lib/mysql
    env_file: "./requirements/mariadb/.env"
    secrets:
      - db-password
      - db-root-password
    restart: always
  redis:
    image: redis
    build: ./requirements/redis
    pull_policy: build
    networks:
      - docker-network
    restart: always

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ${WP_DATA_HOST_PATH}
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${DB_DATA_HOST_PATH}
      o: bind

networks:
  docker-network:

secrets:
  server-certificate:
    file: ../secrets/cert.crt
  server-certificate-key:
    file: ../secrets/cert.key
  db-password:
    file: ../secrets/db_password.txt
  db-root-password:
    file: ../secrets/db_root_password.txt
